import Head from 'next/head'

import Card from '@/entities/card/ui'

import { ICard, IColor, IImage } from '@/entities/card/model'

export default function Home() {
    const colors: Array<IColor> = [
        {
            id: 0,
            name: 'red',
            code: 'EE4444'
        },
        {
            id: 1,
            name: 'blue',
            code: '3C81F6'
        },
        {
            id: 2,
            name: 'black',
            code: '000000'
        }
    ]

    const images: Array<IImage> = [
        {
            id: 0,
            colorId: 0,
            src: 'red.png',
            alt: 'red'
        },
        {
            id: 1,
            colorId: 1,
            src: 'blue.png',
            alt: 'blue'
        },
        {
            id: 2,
            colorId: 2,
            src: 'black.png',
            alt: 'black'
        }
    ]

    const card: ICard = {
        id: 0,
        name: 'Zebronics head phone',
        price: 150,
        description:
            'A portable headphone with a battery life of 20 hours and IP67 rating. Comes with a 3 years warranty.',
        colors,
        images
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="main">
                <Card
                    id={card.id}
                    name={card.name}
                    price={card.price}
                    description={card.description}
                    colors={card.colors}
                    images={card.images}
                />
            </main>
        </>
    )
}
